# Makefile to generate README.md and display project details

README.md:
	@echo "# Guessing Game" > README.md
	@echo "This is a simple guessing game in Bash where the user guesses the number of files in the current directory." >> README.md
	@echo "" >> README.md
	@echo "## Date and Time" >> README.md
	@date >> README.md
	@echo "" >> README.md
	@echo "## Number of Lines in guessinggame.sh" >> README.md
	@wc -l guessinggame.sh | awk '{ print $1 }' >> README.md
	@echo "" >> README.md
	@echo "## Project Files" >> README.md
	@echo "This project contains the following files:" >> README.md
	@echo "- guessinggame.sh" >> README.md
	@echo "- Makefile" >> README.md
	@echo "- README.md (generated by Makefile)" >> README.md

# Clean the project (optional)
clean:
	rm -f README.md
